// All 360 animals across 6 continents
// [name, scientific, emoji, category, status, wiki, lat, lon, habitat, continent, continentFile]
const _D=[
// ── AFRICA ──────────────────────────────────────────────────────────────────
['African Bush Elephant','Loxodonta africana','🐘','mammals','Vulnerable','African_bush_elephant',-2.64,37.26,'Amboseli National Park, Kenya','Africa','africa.html'],
['African Forest Elephant','Loxodonta cyclotis','🐘','mammals','Critically Endangered','African_forest_elephant',0.50,18.00,'Congo Basin, DRC','Africa','africa.html'],
['Lion','Panthera leo','🦁','mammals','Vulnerable','Lion',-1.50,35.10,'Masai Mara, Kenya','Africa','africa.html'],
['Cheetah','Acinonyx jubatus','🐆','mammals','Vulnerable','Cheetah',-2.33,34.83,'Serengeti, Tanzania','Africa','africa.html'],
['Leopard','Panthera pardus','🐆','mammals','Vulnerable','Leopard',-24.0,31.5,'Kruger National Park, South Africa','Africa','africa.html'],
['Giraffe','Giraffa camelopardalis','🦒','mammals','Vulnerable','Giraffe',-2.71,37.35,'Amboseli National Park, Kenya','Africa','africa.html'],
['Common Hippopotamus','Hippopotamus amphibius','🦛','mammals','Vulnerable','Hippopotamus',4.00,32.50,'Victoria Nile, Uganda','Africa','africa.html'],
['White Rhinoceros','Ceratotherium simum','🦏','mammals','Near Threatened','White_rhinoceros',-28.0,32.0,'Hluhluwe-iMfolozi Park, KwaZulu-Natal','Africa','africa.html'],
['Black Rhinoceros','Diceros bicornis','🦏','mammals','Critically Endangered','Black_rhinoceros',-3.5,36.0,'Ngorongoro Crater, Tanzania','Africa','africa.html'],
['Mountain Gorilla','Gorilla beringei beringei','🦍','mammals','Endangered','Mountain_gorilla',-1.48,29.52,'Virunga Mountains, Rwanda','Africa','africa.html'],
['Common Chimpanzee','Pan troglodytes','🐒','mammals','Endangered','Chimpanzee',-4.50,15.50,'Nouabalé-Ndoki, Congo','Africa','africa.html'],
['African Wild Dog','Lycaon pictus','🐕','mammals','Endangered','African_wild_dog',-18.0,24.0,'Okavango Delta, Botswana','Africa','africa.html'],
['Spotted Hyena','Crocuta crocuta','🦬','mammals','Least Concern','Spotted_hyena',-3.5,36.5,'Ngorongoro Conservation Area, Tanzania','Africa','africa.html'],
['Meerkat','Suricata suricatta','🦦','mammals','Least Concern','Meerkat',-26.5,20.5,'Kalahari Desert, Botswana','Africa','africa.html'],
['Honey Badger','Mellivora capensis','🦡','mammals','Least Concern','Honey_badger',-20.0,23.0,'Okavango, Botswana','Africa','africa.html'],
['Mandrill','Mandrillus sphinx','🐒','mammals','Vulnerable','Mandrill',0.5,12.0,'Lopé National Park, Gabon','Africa','africa.html'],
['Serval','Leptailurus serval','🐱','mammals','Least Concern','Serval',-1.3,36.8,'Nairobi National Park, Kenya','Africa','africa.html'],
['Aardvark','Orycteropus afer','🐷','mammals','Least Concern','Aardvark',-24.0,24.0,'Kgalagadi Transfrontier Park, Botswana','Africa','africa.html'],
['Ground Pangolin','Smutsia temminckii','🐾','mammals','Vulnerable','Ground_pangolin',4.0,12.0,'Cameroon','Africa','africa.html'],
['Cape Buffalo','Syncerus caffer','🐂','mammals','Near Threatened','African_buffalo',-2.0,34.5,'Serengeti National Park, Tanzania','Africa','africa.html'],
['Plains Zebra','Equus quagga','🦓','mammals','Near Threatened','Plains_zebra',-2.5,34.9,'Serengeti, Tanzania','Africa','africa.html'],
['Common Warthog','Phacochoerus africanus','🐗','mammals','Least Concern','Common_warthog',-2.5,37.5,'Tsavo East National Park, Kenya','Africa','africa.html'],
['Nile Crocodile','Crocodylus niloticus','🐊','reptiles','Least Concern','Nile_crocodile',24.09,32.90,'Nile River, Egypt','Africa','africa.html'],
['Black Mamba','Dendroaspis polylepis','🐍','reptiles','Least Concern','Black_mamba',-13.5,32.5,'Luangwa Valley, Zambia','Africa','africa.html'],
['Puff Adder','Bitis arietans','🐍','reptiles','Least Concern','Puff_adder',-29.0,26.0,'Free State, South Africa','Africa','africa.html'],
['Gaboon Viper','Bitis gabonica','🐍','reptiles','Least Concern','Gaboon_viper',0.5,25.5,'Congo Rainforest, DRC','Africa','africa.html'],
['Boomslang','Dispholidus typus','🐍','reptiles','Least Concern','Boomslang',-29.5,30.0,'KwaZulu-Natal, South Africa','Africa','africa.html'],
['African Rock Python','Python sebae','🐍','reptiles','Least Concern','African_rock_python',0.0,30.0,'Queen Elizabeth NP, Uganda','Africa','africa.html'],
['Nile Monitor','Varanus niloticus','🦎','reptiles','Least Concern','Nile_monitor',4.0,32.0,'Nile River, South Sudan','Africa','africa.html'],
['Panther Chameleon','Furcifer pardalis','🦎','reptiles','Least Concern','Panther_chameleon',-15.0,48.5,'Nosy Be, Madagascar','Africa','africa.html'],
['Green Mamba','Dendroaspis angusticeps','🐍','reptiles','Least Concern','Eastern_green_mamba',-4.5,38.5,'Coastal Forests, Tanzania','Africa','africa.html'],
['Nile Softshell Turtle','Trionyx triunguis','🐢','reptiles','Vulnerable','African_softshell_turtle',23.0,32.5,'Upper Nile, Sudan','Africa','africa.html'],
['Common Ostrich','Struthio camelus','🦩','birds','Least Concern','Common_ostrich',11.00,15.00,'Sahel Savanna, Chad','Africa','africa.html'],
['Secretarybird','Sagittarius serpentarius','🦅','birds','Vulnerable','Secretarybird',-26.0,28.0,'Highveld, South Africa','Africa','africa.html'],
['African Fish Eagle','Haliaeetus vocifer','🦅','birds','Least Concern','African_fish_eagle',-1.5,34.0,'Lake Victoria, Kenya/Uganda','Africa','africa.html'],
['Lesser Flamingo','Phoeniconaias minor','🦩','birds','Near Threatened','Lesser_flamingo',-2.0,36.1,'Lake Nakuru, Kenya','Africa','africa.html'],
['Shoebill','Balaeniceps rex','🐦','birds','Vulnerable','Shoebill',3.5,32.0,'Murchison Falls, Uganda','Africa','africa.html'],
['Crowned Eagle','Stephanoaetus coronatus','🦅','birds','Vulnerable','African_crowned_eagle',-26.5,32.5,'Kruger National Park, South Africa','Africa','africa.html'],
['Kori Bustard','Ardeotis kori','🦢','birds','Near Threatened','Kori_bustard',-3.0,36.0,'Ngorongoro Conservation Area, Tanzania','Africa','africa.html'],
['African Penguin','Spheniscus demersus','🐧','birds','Endangered','African_penguin',-33.9,18.4,'Boulders Beach, Cape Town','Africa','africa.html'],
['Marabou Stork','Leptoptilos crumenifer','🦢','birds','Least Concern','Marabou_stork',-1.5,36.8,'Nairobi, Kenya','Africa','africa.html'],
['Lilac-breasted Roller','Coracias caudatus','🐦','birds','Least Concern','Lilac-breasted_roller',-2.5,34.0,'Serengeti, Tanzania','Africa','africa.html'],
['African Grey Parrot','Psittacus erithacus','🦜','birds','Endangered','African_grey_parrot',4.0,20.0,'Congo Basin, DRC','Africa','africa.html'],
['Southern Ground Hornbill','Bucorvus leadbeateri','🐦','birds','Vulnerable','Southern_ground_hornbill',-24.0,31.5,'Kruger National Park, South Africa','Africa','africa.html'],
['White-backed Vulture','Gyps africanus','🦅','birds','Critically Endangered','White-backed_vulture',-2.0,35.0,'Serengeti Ecosystem, Tanzania','Africa','africa.html'],
['Superb Starling','Lamprotornis superbus','🐦','birds','Least Concern','Superb_starling',-2.0,37.0,'Amboseli National Park, Kenya','Africa','africa.html'],
['Goliath Tigerfish','Hydrocynus goliath','🐟','fish','Least Concern','Goliath_tigerfish',-4.0,25.0,'Congo River, DRC','Africa','africa.html'],
['African Lungfish','Protopterus annectens','🐟','fish','Least Concern','West_African_lungfish',8.0,4.0,'West African River Floodplains','Africa','africa.html'],
['Nile Tilapia','Oreochromis niloticus','🐟','fish','Least Concern','Nile_tilapia',2.0,32.5,'Lake Victoria, East Africa','Africa','africa.html'],
['Electric Catfish','Malapterurus electricus','🐟','fish','Least Concern','Electric_catfish',14.0,32.0,'Nile River, Sudan','Africa','africa.html'],
['Nile Perch','Lates niloticus','🐟','fish','Least Concern','Nile_perch',-1.0,33.0,'Lake Victoria, East Africa','Africa','africa.html'],
['Bull Shark','Carcharhinus leucas','🦈','fish','Vulnerable','Bull_shark',-18.0,35.5,'Zambezi River Mouth, Mozambique','Africa','africa.html'],
['Goliath Beetle','Goliathus goliatus','🪲','insects','Least Concern','Goliath_beetle',1.00,15.00,'Congo Rainforest, DRC','Africa','africa.html'],
['African Driver Ant','Dorylus wilverthi','🐜','insects','Least Concern','Driver_ant',-4.0,21.5,'Congo Forest, DRC','Africa','africa.html'],
['African Honeybee','Apis mellifera scutellata','🐝','insects','Least Concern','Africanized_bee',-12.0,28.0,'Zambia','Africa','africa.html'],
['Dung Beetle','Scarabaeus sacer','🪲','insects','Least Concern','Dung_beetle',-3.5,30.0,'Tanzanian Savanna','Africa','africa.html'],
['African Bullfrog','Pyxicephalus adspersus','🐸','amphibians','Least Concern','African_bullfrog',-20.00,23.00,'Kalahari, Botswana','Africa','africa.html'],
['Goliath Frog','Conraua goliath','🐸','amphibians','Endangered','Goliath_frog',3.5,10.5,'Rainforest Rivers, Cameroon','Africa','africa.html'],
['African Clawed Frog','Xenopus laevis','🐸','amphibians','Least Concern','African_clawed_frog',-30.0,25.0,'Eastern Cape, South Africa','Africa','africa.html'],
['African Reed Frog','Hyperolius viridiflavus','🐸','amphibians','Least Concern','African_reed_frog',-3.0,40.0,'Kenya Coast','Africa','africa.html'],
// ── ASIA ─────────────────────────────────────────────────────────────────────
['Bengal Tiger','Panthera tigris tigris','🐅','mammals','Endangered','Bengal_tiger',21.95,89.18,'Sundarbans, Bangladesh','Asia','asia.html'],
['Giant Panda','Ailuropoda melanoleuca','🐼','mammals','Vulnerable','Giant_panda',33.85,107.60,'Qinling Mountains, China','Asia','asia.html'],
['Snow Leopard','Panthera uncia','🐱','mammals','Vulnerable','Snow_leopard',27.90,86.90,'Himalayas, Nepal','Asia','asia.html'],
['Red Panda','Ailurus fulgens','🐾','mammals','Endangered','Red_panda',27.50,88.50,'Eastern Himalayas, Nepal','Asia','asia.html'],
['Japanese Macaque','Macaca fuscata','🐒','mammals','Least Concern','Japanese_macaque',36.74,138.20,'Jigokudani Hot Springs, Nagano','Asia','asia.html'],
['Proboscis Monkey','Nasalis larvatus','🐒','mammals','Endangered','Proboscis_monkey',5.41,118.01,'Kinabatangan River, Borneo','Asia','asia.html'],
['Asian Elephant','Elephas maximus','🐘','mammals','Endangered','Asian_elephant',7.97,80.82,'Minneriya National Park, Sri Lanka','Asia','asia.html'],
['Bornean Orangutan','Pongo pygmaeus','🦧','mammals','Critically Endangered','Bornean_orangutan',1.50,110.50,'Danum Valley, Borneo','Asia','asia.html'],
['Indian Rhinoceros','Rhinoceros unicornis','🦏','mammals','Vulnerable','Indian_rhinoceros',26.60,92.90,'Kaziranga National Park, Assam','Asia','asia.html'],
['Clouded Leopard','Neofelis nebulosa','🐆','mammals','Vulnerable','Clouded_leopard',27.50,88.00,'Bhutan Foothills','Asia','asia.html'],
['Binturong','Arctictis binturong','🦦','mammals','Vulnerable','Binturong',4.50,117.50,'Danum Valley, Borneo','Asia','asia.html'],
['Sun Bear','Helarctos malayanus','🐻','mammals','Vulnerable','Sun_bear',4.00,116.00,'Borneo Rainforest','Asia','asia.html'],
['Golden Snub-nosed Monkey','Rhinopithecus roxellana','🐒','mammals','Endangered','Golden_snub-nosed_monkey',32.00,107.50,'Qinling Mountains, China','Asia','asia.html'],
['Bactrian Camel','Camelus bactrianus','🐪','mammals','Critically Endangered','Bactrian_camel',44.00,103.00,'Gobi Desert, Mongolia','Asia','asia.html'],
['Malayan Tapir','Tapirus indicus','🐷','mammals','Endangered','Malayan_tapir',3.50,103.00,'Taman Negara, Malaysia','Asia','asia.html'],
['Amur Leopard','Panthera pardus orientalis','🐆','mammals','Critically Endangered','Amur_leopard',43.50,135.00,'Land of the Leopard NP, Russia','Asia','asia.html'],
['Siberian Tiger','Panthera tigris altaica','🐅','mammals','Endangered','Siberian_tiger',45.00,133.50,'Sikhote-Alin Biosphere Reserve, Russia','Asia','asia.html'],
['Saiga Antelope','Saiga tatarica','🦌','mammals','Critically Endangered','Saiga_antelope',48.50,61.00,'Betpak-Dala Steppe, Kazakhstan','Asia','asia.html'],
['Wild Yak','Bos mutus','🐂','mammals','Vulnerable','Yak',31.50,91.50,'Tibetan Plateau, China','Asia','asia.html'],
['Irrawaddy Dolphin','Orcaella brevirostris','🐬','mammals','Endangered','Irrawaddy_dolphin',16.50,96.50,'Irrawaddy River, Myanmar','Asia','asia.html'],
['Komodo Dragon','Varanus komodoensis','🦎','reptiles','Endangered','Komodo_dragon',-8.55,119.48,'Komodo Island, Indonesia','Asia','asia.html'],
['King Cobra','Ophiophagus hannah','🐍','reptiles','Vulnerable','King_cobra',11.00,76.00,'Western Ghats, India','Asia','asia.html'],
['Reticulated Python','Malayopython reticulatus','🐍','reptiles','Least Concern','Reticulated_python',3.00,101.00,'Taman Negara, Malaysia','Asia','asia.html'],
['Gharial','Gavialis gangeticus','🐊','reptiles','Critically Endangered','Gharial',27.50,83.00,'Chitwan National Park, Nepal','Asia','asia.html'],
['Indian Star Tortoise','Geochelone elegans','🐢','reptiles','Vulnerable','Indian_star_tortoise',12.00,78.00,'Deccan Plateau, India','Asia','asia.html'],
['Mugger Crocodile','Crocodylus palustris','🐊','reptiles','Vulnerable','Mugger_crocodile',22.50,72.50,'Nal Sarovar, Gujarat, India','Asia','asia.html'],
['Water Monitor','Varanus salvator','🦎','reptiles','Least Concern','Water_monitor',3.00,101.50,'Peninsular Malaysia','Asia','asia.html'],
['Tokay Gecko','Gekko gecko','🦎','reptiles','Least Concern','Tokay_gecko',14.00,101.00,'Thailand','Asia','asia.html'],
['Flying Dragon','Draco volans','🦎','reptiles','Least Concern','Draco_volans',3.00,102.00,'Rainforests of Malaysia','Asia','asia.html'],
['Chinese Softshell Turtle','Pelodiscus sinensis','🐢','reptiles','Vulnerable','Chinese_softshell_turtle',30.00,120.00,'Yangtze Delta, China','Asia','asia.html'],
['Indian Peafowl','Pavo cristatus','🦚','birds','Least Concern','Indian_peafowl',21.50,82.00,'Kanha Tiger Reserve, India','Asia','asia.html'],
['Japanese Crane','Grus japonensis','🦢','birds','Vulnerable','Red-crowned_crane',43.00,144.00,'Kushiro Marshland, Hokkaido','Asia','asia.html'],
['Great Hornbill','Buceros bicornis','🐦','birds','Vulnerable','Great_hornbill',11.00,77.00,'Nilgiri Hills, India','Asia','asia.html'],
['Bali Myna','Leucopsar rothschildi','🐦','birds','Critically Endangered','Bali_myna',-8.10,114.50,'Bali Barat National Park, Bali','Asia','asia.html'],
['Philippine Eagle','Pithecophaga jefferyi','🦅','birds','Critically Endangered','Philippine_eagle',7.00,125.00,'Mount Apo, Mindanao','Asia','asia.html'],
['Himalayan Monal','Lophophorus impejanus','🦚','birds','Least Concern','Himalayan_monal',28.00,84.00,'Annapurna Conservation Area, Nepal','Asia','asia.html'],
['Red Junglefowl','Gallus gallus','🐓','birds','Least Concern','Red_junglefowl',15.00,100.00,'Doi Inthanon, Thailand','Asia','asia.html'],
['Mandarin Duck','Aix galericulata','🦆','birds','Least Concern','Mandarin_duck',35.00,135.00,'Kyoto, Japan','Asia','asia.html'],
['Siberian Crane','Leucogeranus leucogeranus','🦢','birds','Critically Endangered','Siberian_crane',70.00,60.00,'Ob River Delta, Russia','Asia','asia.html'],
['Sarus Crane','Antigone antigana','🦢','birds','Vulnerable','Sarus_crane',27.00,78.00,'Uttar Pradesh, India','Asia','asia.html'],
['White-bellied Sea Eagle','Haliaeetus leucogaster','🦅','birds','Least Concern','White-bellied_sea_eagle',13.00,80.00,'South India Coast','Asia','asia.html'],
['Great White Pelican','Pelecanus onocrotalus','🐦','birds','Least Concern','Great_white_pelican',52.00,68.00,'Kurgaldzhin, Kazakhstan','Asia','asia.html'],
['Mekong Giant Catfish','Pangasianodon gigas','🐟','fish','Critically Endangered','Mekong_giant_catfish',20.00,100.50,'Upper Mekong, Laos','Asia','asia.html'],
['Giant Freshwater Stingray','Urogymnus polylepis','🐟','fish','Endangered','Giant_freshwater_stingray',13.50,100.50,'Mekong River, Thailand','Asia','asia.html'],
['Asian Arowana','Scleropages formosus','🐟','fish','Endangered','Asian_arowana',0.50,109.50,'Kapuas River, Borneo','Asia','asia.html'],
['Giant Snakehead','Channa micropeltes','🐟','fish','Least Concern','Giant_snakehead',11.50,104.50,'Mekong Delta, Cambodia','Asia','asia.html'],
['Japanese Pufferfish','Takifugu rubripes','🐡','fish','Least Concern','Tiger_pufferfish',34.00,136.00,'Inland Sea, Japan','Asia','asia.html'],
['Mudskipper','Boleophthalmus boddarti','🐟','fish','Least Concern','Mudskipper',22.50,88.50,'Sundarbans, India','Asia','asia.html'],
['Asian Giant Hornet','Vespa mandarinia','🐝','insects','Least Concern','Asian_giant_hornet',36.50,138.00,'Honshu, Japan','Asia','asia.html'],
['Atlas Moth','Attacus atlas','🦋','insects','Least Concern','Atlas_moth',23.00,113.00,'South China/Southeast Asia','Asia','asia.html'],
['Giant Water Bug','Lethocerus indicus','🪲','insects','Least Concern','Giant_water_bug',15.00,100.00,'Central Thailand Wetlands','Asia','asia.html'],
['Orchid Mantis','Hymenopus coronatus','🌸','insects','Least Concern','Orchid_mantis',3.50,103.50,'Rainforests of Malaysia','Asia','asia.html'],
['Jewel Beetle','Chrysochroa rajah','🪲','insects','Least Concern','Chrysochroa_rajah',5.00,118.00,'Borneo','Asia','asia.html'],
['Giant Walking Stick','Phobaeticus chani','🪲','insects','Least Concern','Phobaeticus_chani',5.00,118.00,'Mount Kinabalu, Borneo','Asia','asia.html'],
['Chinese Giant Salamander','Andrias davidianus','🫧','amphibians','Critically Endangered','Chinese_giant_salamander',30.60,114.30,'Yangtze River tributaries, China','Asia','asia.html'],
['Japanese Giant Salamander','Andrias japonicus','🫧','amphibians','Near Threatened','Japanese_giant_salamander',35.00,135.50,'Hii River, Shimane, Japan','Asia','asia.html'],
['Indian Purple Frog','Nasikabatrachus sahyadrensis','🐸','amphibians','Endangered','Purple_frog',10.50,76.50,'Kerala, Western Ghats','Asia','asia.html'],
['Bornean Horned Frog','Megophrys nasuta','🐸','amphibians','Least Concern','Malayan_horned_frog',4.50,117.00,'Danum Valley, Borneo','Asia','asia.html'],
['Malabar Gliding Frog','Rhacophorus malabaricus','🐸','amphibians','Least Concern','Malabar_gliding_frog',11.50,75.50,'Malabar Coast, Kerala, India','Asia','asia.html'],
['Giant Tree Frog','Rhacophorus reinwardtii','🐸','amphibians','Least Concern','Reinwardt\'s_flying_frog',5.00,118.00,'Lowland Rainforest, Borneo','Asia','asia.html'],
// ── NORTH AMERICA ─────────────────────────────────────────────────────────────
['Grizzly Bear','Ursus arctos horribilis','🐻','mammals','Least Concern','Grizzly_bear',44.43,-110.59,'Yellowstone National Park, Wyoming','North America','northamerica.html'],
['American Bison','Bison bison','🦬','mammals','Near Threatened','American_bison',43.75,-102.49,'Badlands, South Dakota','North America','northamerica.html'],
['Gray Wolf','Canis lupus','🐺','mammals','Least Concern','Gray_wolf',44.80,-110.55,'Yellowstone National Park, Wyoming','North America','northamerica.html'],
['Polar Bear','Ursus maritimus','🐻‍❄️','mammals','Vulnerable','Polar_bear',58.77,-93.82,'Churchill, Manitoba, Canada','North America','northamerica.html'],
['Moose','Alces alces','🦌','mammals','Least Concern','Moose',60.50,-147.50,'Kenai Peninsula, Alaska','North America','northamerica.html'],
['American Black Bear','Ursus americanus','🐻','mammals','Least Concern','American_black_bear',35.70,-83.50,'Great Smoky Mountains, Tennessee','North America','northamerica.html'],
['Pronghorn','Antilocapra americana','🦌','mammals','Least Concern','Pronghorn',43.00,-104.00,'Wyoming Great Basin','North America','northamerica.html'],
['Mountain Lion','Puma concolor','🦁','mammals','Least Concern','Cougar',36.50,-118.50,'Sierra Nevada, California','North America','northamerica.html'],
['Beluga Whale','Delphinapterus leucas','🐳','mammals','Least Concern','Beluga_whale',63.00,-90.50,'Hudson Bay, Canada','North America','northamerica.html'],
['West Indian Manatee','Trichechus manatus','🐘','mammals','Vulnerable','West_Indian_manatee',27.50,-82.50,'Crystal River, Florida','North America','northamerica.html'],
['Narwhal','Monodon monoceros','🦄','mammals','Least Concern','Narwhal',72.00,-80.00,'Baffin Bay, Nunavut','North America','northamerica.html'],
['Wolverine','Gulo gulo','🦡','mammals','Least Concern','Wolverine_(animal)',48.50,-113.60,'Glacier National Park, Montana','North America','northamerica.html'],
['North American River Otter','Lontra canadensis','🦦','mammals','Least Concern','North_American_river_otter',39.00,-76.50,'Chesapeake Bay Watershed, Maryland','North America','northamerica.html'],
['Nine-banded Armadillo','Dasypus novemcinctus','🐾','mammals','Least Concern','Nine-banded_armadillo',30.00,-97.00,'Central Texas','North America','northamerica.html'],
['Black-footed Ferret','Mustela nigripes','🐾','mammals','Endangered','Black-footed_ferret',43.00,-104.00,'Thunder Basin, Wyoming','North America','northamerica.html'],
['Snowshoe Hare','Lepus americanus','🐰','mammals','Least Concern','Snowshoe_hare',55.50,-120.00,'Boreal Forest, British Columbia','North America','northamerica.html'],
['American Pika','Ochotona princeps','🐾','mammals','Least Concern','American_pika',37.80,-119.50,'Yosemite High Country, California','North America','northamerica.html'],
['Sea Otter','Enhydra lutris','🦦','mammals','Endangered','Sea_otter',36.60,-121.90,'Monterey Bay, California','North America','northamerica.html'],
['White-tailed Deer','Odocoileus virginianus','🦌','mammals','Least Concern','White-tailed_deer',44.00,-89.00,'Wisconsin','North America','northamerica.html'],
['Humpback Whale','Megaptera novaeangliae','🐋','mammals','Least Concern','Humpback_whale',46.00,-124.00,'Pacific Coast, Oregon/Washington','North America','northamerica.html'],
['American Alligator','Alligator mississippiensis','🐊','reptiles','Least Concern','American_alligator',25.51,-80.93,'Everglades, Florida','North America','northamerica.html'],
['American Crocodile','Crocodylus acutus','🐊','reptiles','Vulnerable','American_crocodile',25.20,-80.80,'Florida Bay & Caribbean Coast','North America','northamerica.html'],
['Gila Monster','Heloderma suspectum','🦎','reptiles','Near Threatened','Gila_monster',33.50,-112.00,'Sonoran Desert, Arizona','North America','northamerica.html'],
['Timber Rattlesnake','Crotalus horridus','🐍','reptiles','Least Concern','Timber_rattlesnake',41.50,-74.50,'Catskill Mountains, New York','North America','northamerica.html'],
['Common Snapping Turtle','Chelydra serpentina','🐢','reptiles','Least Concern','Common_snapping_turtle',43.00,-76.00,'Upstate New York','North America','northamerica.html'],
['Leatherback Sea Turtle','Dermochelys coriacea','🐢','reptiles','Vulnerable','Leatherback_sea_turtle',10.50,-61.50,'Trinidad, Caribbean','North America','northamerica.html'],
['Western Diamondback Rattlesnake','Crotalus atrox','🐍','reptiles','Least Concern','Western_diamondback_rattlesnake',32.00,-106.00,'Chihuahuan Desert, New Mexico','North America','northamerica.html'],
['Alligator Snapping Turtle','Macrochelys temminckii','🐢','reptiles','Vulnerable','Alligator_snapping_turtle',31.00,-91.00,'Mississippi River System, Louisiana','North America','northamerica.html'],
['Bald Eagle','Haliaeetus leucocephalus','🦅','birds','Least Concern','Bald_eagle',58.30,-134.42,'Inside Passage, Alaska','North America','northamerica.html'],
['California Condor','Gymnogyps californianus','🦅','birds','Critically Endangered','California_condor',36.10,-112.10,'Grand Canyon, Arizona','North America','northamerica.html'],
['Whooping Crane','Grus americana','🦢','birds','Endangered','Whooping_crane',28.00,-97.00,'Aransas National Wildlife Refuge, Texas','North America','northamerica.html'],
['American Flamingo','Phoenicopterus ruber','🦩','birds','Least Concern','American_flamingo',25.00,-81.00,'Florida Bay, Florida','North America','northamerica.html'],
['Atlantic Puffin','Fratercula arctica','🐦','birds','Vulnerable','Atlantic_puffin',47.50,-52.50,'Cape St. Mary\'s, Newfoundland','North America','northamerica.html'],
['Great Horned Owl','Bubo virginianus','🦉','birds','Least Concern','Great_horned_owl',44.00,-110.00,'Yellowstone Ecosystem, Wyoming','North America','northamerica.html'],
['Ruby-throated Hummingbird','Archilochus colubris','🐦','birds','Least Concern','Ruby-throated_hummingbird',38.00,-84.00,'Kentucky bluegrass region','North America','northamerica.html'],
['Osprey','Pandion haliaetus','🦅','birds','Least Concern','Osprey',39.00,-76.50,'Chesapeake Bay, Maryland','North America','northamerica.html'],
['Sandhill Crane','Antigone canadensis','🦢','birds','Least Concern','Sandhill_crane',40.50,-98.50,'Platte River, Nebraska','North America','northamerica.html'],
['Roseate Spoonbill','Platalea ajaja','🦩','birds','Least Concern','Roseate_spoonbill',25.80,-81.00,'Ten Thousand Islands, Everglades','North America','northamerica.html'],
['Great Blue Heron','Ardea herodias','🐦','birds','Least Concern','Great_blue_heron',38.50,-76.50,'Chesapeake Bay, Maryland','North America','northamerica.html'],
['Trumpeter Swan','Cygnus buccinator','🦢','birds','Least Concern','Trumpeter_swan',43.50,-110.50,'Yellowstone Lake, Wyoming','North America','northamerica.html'],
['Great White Shark','Carcharodon carcharias','🦈','fish','Vulnerable','Great_white_shark',37.70,-123.00,'Farallon Islands, California','North America','northamerica.html'],
['Chinook Salmon','Oncorhynchus tshawytscha','🐟','fish','Least Concern','Chinook_salmon',47.50,-121.00,'Cascade Mountains, Washington','North America','northamerica.html'],
['Lake Sturgeon','Acipenser fulvescens','🐟','fish','Vulnerable','Lake_sturgeon',43.50,-83.50,'Lake Huron, Michigan','North America','northamerica.html'],
['Alligator Gar','Atractosteus spatula','🐟','fish','Least Concern','Alligator_gar',31.00,-92.00,'Atchafalaya Basin, Louisiana','North America','northamerica.html'],
['American Paddlefish','Polyodon spathula','🐟','fish','Vulnerable','American_paddlefish',38.00,-90.00,'Missouri River, Missouri','North America','northamerica.html'],
['Sockeye Salmon','Oncorhynchus nerka','🐟','fish','Least Concern','Sockeye_salmon',51.00,-125.00,'Johnstone Strait, British Columbia','North America','northamerica.html'],
['Atlantic Horseshoe Crab','Limulus polyphemus','🦀','fish','Vulnerable','Atlantic_horseshoe_crab',39.00,-75.00,'Delaware Bay, New Jersey','North America','northamerica.html'],
['Largemouth Bass','Micropterus salmoides','🐟','fish','Least Concern','Largemouth_bass',31.00,-87.00,'Alabama River System','North America','northamerica.html'],
['Monarch Butterfly','Danaus plexippus','🦋','insects','Endangered','Monarch_butterfly',19.62,-100.25,'Monarch Biosphere Reserve, Michoacán','North America','northamerica.html'],
['Luna Moth','Actias luna','🦋','insects','Least Concern','Luna_moth',38.00,-84.00,'Eastern Deciduous Forests, Kentucky','North America','northamerica.html'],
['Eastern Firefly','Photinus pyralis','✨','insects','Least Concern','Photinus_pyralis',35.70,-84.00,'Great Smoky Mountains, Tennessee','North America','northamerica.html'],
['American Bumblebee','Bombus pensylvanicus','🐝','insects','Vulnerable','American_bumblebee',38.00,-95.00,'Tallgrass Prairie, Kansas','North America','northamerica.html'],
['Mountain Pine Beetle','Dendroctonus ponderosae','🪲','insects','Least Concern','Mountain_pine_beetle',50.00,-119.00,'Interior British Columbia','North America','northamerica.html'],
['Cecropia Moth','Hyalophora cecropia','🦋','insects','Least Concern','Cecropia_moth',42.00,-85.00,'Deciduous Forests, Michigan','North America','northamerica.html'],
['American Bullfrog','Lithobates catesbeianus','🐸','amphibians','Least Concern','American_bullfrog',29.95,-90.07,'Mississippi Delta, Louisiana','North America','northamerica.html'],
['Eastern Hellbender','Cryptobranchus alleganiensis','🐸','amphibians','Near Threatened','Hellbender',37.00,-80.00,'Appalachian Mountain Streams, Virginia','North America','northamerica.html'],
['Axolotl','Ambystoma mexicanum','🐸','amphibians','Critically Endangered','Axolotl',19.45,-99.10,'Lake Xochimilco, Mexico City','North America','northamerica.html'],
['California Red-legged Frog','Rana draytonii','🐸','amphibians','Vulnerable','California_red-legged_frog',37.50,-122.00,'Marin County, California','North America','northamerica.html'],
// ── SOUTH AMERICA ─────────────────────────────────────────────────────────────
['Jaguar','Panthera onca','🐆','mammals','Near Threatened','Jaguar',-3.10,-60.03,'Amazon Rainforest, Brazil','South America','southamerica.html'],
['Capybara','Hydrochoerus hydrochaeris','🦫','mammals','Least Concern','Capybara',-6.00,-67.00,'Pantanal Wetlands, Brazil','South America','southamerica.html'],
['Giant Anteater','Myrmecophaga tridactyla','🦔','mammals','Vulnerable','Giant_anteater',-15.00,-47.90,'Brazilian Cerrado','South America','southamerica.html'],
['South American Tapir','Tapirus terrestris','🦏','mammals','Vulnerable','South_American_tapir',-4.50,-73.00,'Peruvian Amazon','South America','southamerica.html'],
['Amazon River Dolphin','Inia geoffrensis','🐬','mammals','Endangered','Amazon_river_dolphin',-3.00,-60.50,'Amazon River, Brazil','South America','southamerica.html'],
['Spectacled Bear','Tremarctos ornatus','🐻','mammals','Vulnerable','Spectacled_bear',-6.70,-78.50,'Cloud Forest, Northern Peru','South America','southamerica.html'],
['Maned Wolf','Chrysocyon brachyurus','🦊','mammals','Near Threatened','Maned_wolf',-14.00,-47.00,'Brazilian Cerrado','South America','southamerica.html'],
['Giant Otter','Pteronura brasiliensis','🦦','mammals','Endangered','Giant_otter',-10.00,-65.00,'Bolivian Amazon','South America','southamerica.html'],
['Ocelot','Leopardus pardalis','🐆','mammals','Least Concern','Ocelot',-1.00,-54.50,'Amazon Basin, Pará, Brazil','South America','southamerica.html'],
['Pygmy Marmoset','Cebuella pygmaea','🐒','mammals','Vulnerable','Pygmy_marmoset',-3.50,-72.50,'Ecuadorian Amazon','South America','southamerica.html'],
['Black Howler Monkey','Alouatta caraya','🐒','mammals','Least Concern','Black_howler_monkey',-20.00,-58.00,'Pantanal, Paraguay','South America','southamerica.html'],
['White-faced Spider Monkey','Ateles marginatus','🐒','mammals','Endangered','Ateles_marginatus',-6.00,-55.00,'Lower Amazon, Brazil','South America','southamerica.html'],
['Guanaco','Lama guanicoe','🦙','mammals','Least Concern','Guanaco',-50.00,-72.00,'Torres del Paine, Chile','South America','southamerica.html'],
['Patagonian Mara','Dolichotis patagonum','🐰','mammals','Near Threatened','Patagonian_mara',-42.00,-65.00,'Patagonian Steppe, Argentina','South America','southamerica.html'],
['Giant Armadillo','Priodontes maximus','🐾','mammals','Vulnerable','Giant_armadillo',-8.00,-55.00,'Xingu Indigenous Park, Brazil','South America','southamerica.html'],
['Bush Dog','Speothos venaticus','🐕','mammals','Near Threatened','Bush_dog',-5.00,-60.00,'Amazon Basin, Brazil','South America','southamerica.html'],
['South Andean Deer','Hippocamelus bisulcus','🦌','mammals','Endangered','South_Andean_deer',-47.00,-71.50,'Patagonian Andes, Chile','South America','southamerica.html'],
['Coati','Nasua nasua','🦝','mammals','Least Concern','South_American_coati',-8.00,-63.00,'Rondônia, Brazil','South America','southamerica.html'],
['Franciscana Dolphin','Pontoporia blainvillei','🐬','mammals','Vulnerable','Franciscana_dolphin',-29.00,-50.00,'Rio Grande do Sul Coast, Brazil','South America','southamerica.html'],
['Lowland Paca','Cuniculus paca','🐾','mammals','Least Concern','Lowland_paca',-2.50,-55.00,'Amazon Floodplain, Brazil','South America','southamerica.html'],
['Green Anaconda','Eunectes murinus','🐍','reptiles','Least Concern','Green_anaconda',-6.00,-66.50,'Llanos Wetlands, Venezuela','South America','southamerica.html'],
['Black Caiman','Melanosuchus niger','🐊','reptiles','Least Concern','Black_caiman',-4.00,-70.50,'Amazon Floodplain, Brazil','South America','southamerica.html'],
['Galápagos Marine Iguana','Amblyrhynchus cristatus','🦎','reptiles','Vulnerable','Galápagos_marine_iguana',-0.63,-90.37,'Fernandina Island, Galápagos','South America','southamerica.html'],
['Common Caiman','Caiman crocodilus','🐊','reptiles','Least Concern','Common_caiman',-5.00,-60.00,'Amazon Basin','South America','southamerica.html'],
['Mata Mata','Chelus fimbriata','🐢','reptiles','Least Concern','Mata_mata',-5.00,-68.00,'Orinoco River System, Venezuela','South America','southamerica.html'],
['Galápagos Giant Tortoise','Chelonoidis niger','🐢','reptiles','Vulnerable','Galápagos_tortoise',-0.40,-91.12,'Santa Cruz Island, Galápagos','South America','southamerica.html'],
['South American Rattlesnake','Crotalus durissus','🐍','reptiles','Least Concern','South_American_rattlesnake',-10.00,-55.00,'Brazilian Cerrado','South America','southamerica.html'],
['Emerald Tree Boa','Corallus caninus','🐍','reptiles','Least Concern','Emerald_tree_boa',-3.00,-60.50,'Amazon Floodplain, Brazil','South America','southamerica.html'],
['Andean Condor','Vultur gryphus','🦅','birds','Vulnerable','Andean_condor',-32.50,-70.00,'Andes Mountains, Chile','South America','southamerica.html'],
['Hyacinth Macaw','Anodorhynchus hyacinthinus','🦜','birds','Vulnerable','Hyacinth_macaw',-17.00,-57.00,'Pantanal, Brazil','South America','southamerica.html'],
['Scarlet Macaw','Ara macao','🦜','birds','Least Concern','Scarlet_macaw',4.00,-53.00,'Surinamese Amazon','South America','southamerica.html'],
['Harpy Eagle','Harpia harpyja','🦅','birds','Vulnerable','Harpy_eagle',-5.00,-57.00,'Amazon Basin, Pará, Brazil','South America','southamerica.html'],
['Toco Toucan','Ramphastos toco','🦜','birds','Least Concern','Toco_toucan',-16.00,-47.00,'Brazilian Cerrado','South America','southamerica.html'],
['Greater Rhea','Rhea americana','🐦','birds','Near Threatened','Greater_rhea',-20.00,-57.00,'Pantanal, Brazil','South America','southamerica.html'],
['Blue-footed Booby','Sula nebouxii','🐦','birds','Least Concern','Blue-footed_booby',-0.90,-91.00,'Galápagos Islands, Ecuador','South America','southamerica.html'],
['Cock-of-the-rock','Rupicola peruvianus','🐦','birds','Least Concern','Rupicola_peruvianus',-12.50,-75.50,'Cloud Forest, Peru','South America','southamerica.html'],
['Hoatzin','Opisthocomus hoazin','🐦','birds','Least Concern','Hoatzin',-5.50,-67.50,'Amazon Floodplain, Brazil','South America','southamerica.html'],
['Jabiru Stork','Jabiru mycteria','🦢','birds','Least Concern','Jabiru',-15.00,-57.00,'Pantanal, Mato Grosso, Brazil','South America','southamerica.html'],
['Magellanic Penguin','Spheniscus magellanicus','🐧','birds','Near Threatened','Magellanic_penguin',-45.00,-65.40,'Punta Tombo, Patagonia, Argentina','South America','southamerica.html'],
['Red-bellied Piranha','Pygocentrus nattereri','🐟','fish','Least Concern','Red-bellied_piranha',-6.50,-65.00,'Madeira River, Brazil','South America','southamerica.html'],
['Electric Eel','Electrophorus electricus','⚡','fish','Least Concern','Electric_eel',-5.00,-60.00,'Orinoco River, Venezuela','South America','southamerica.html'],
['Arapaima','Arapaima gigas','🐟','fish','Data Deficient','Arapaima',-4.00,-72.00,'Upper Amazon, Peru','South America','southamerica.html'],
['South American Lungfish','Lepidosiren paradoxa','🐟','fish','Least Concern','South_American_lungfish',-10.00,-65.00,'Madeira Basin, Bolivia','South America','southamerica.html'],
['Pacu','Colossoma macropomum','🐟','fish','Least Concern','Tambaqui',-3.50,-62.00,'Amazon River, Brazil','South America','southamerica.html'],
['Candiru','Vandellia cirrhosa','🐟','fish','Least Concern','Candiru',-4.00,-60.00,'Solimões River, Brazil','South America','southamerica.html'],
['Amazon Bull Shark','Carcharhinus leucas','🦈','fish','Vulnerable','Bull_shark',-3.00,-58.00,'Amazon River at Manaus, Brazil','South America','southamerica.html'],
['Blue Morpho Butterfly','Morpho menelaus','🦋','insects','Least Concern','Morpho_menelaus',-5.00,-57.00,'Amazon Basin, Brazil','South America','southamerica.html'],
['Rhinoceros Beetle','Dynastes hercules','🪲','insects','Least Concern','Dynastes_hercules',4.00,-75.00,'Colombian Cloud Forest','South America','southamerica.html'],
['Amazon Bullet Ant','Paraponera clavata','🐜','insects','Least Concern','Bullet_ant',-2.00,-60.50,'Amazon Rainforest, Brazil','South America','southamerica.html'],
['Glasswinged Butterfly','Greta oto','🦋','insects','Least Concern','Greta_oto',9.00,-79.50,'Cloud Forest, Panama/Colombia','South America','southamerica.html'],
['Leafcutter Ant','Atta cephalotes','🐜','insects','Least Concern','Leafcutter_ant',-5.00,-60.50,'Amazon Basin, Brazil','South America','southamerica.html'],
['Owl Butterfly','Caligo memnon','🦋','insects','Least Concern','Caligo_memnon',-5.00,-78.00,'Andean Foothills, Ecuador','South America','southamerica.html'],
['Blue Poison Dart Frog','Dendrobates tinctorius','🐸','amphibians','Least Concern','Dyeing_poison_dart_frog',4.00,-56.00,'Sipaliwini, Suriname','South America','southamerica.html'],
['Glass Frog','Centrolenidae','🐸','amphibians','Least Concern','Glass_frog',-0.50,-77.00,'Ecuadorian Amazon','South America','southamerica.html'],
['Amazon Milk Frog','Trachycephalus resinifictrix','🐸','amphibians','Least Concern','Amazon_milk_frog',-2.50,-60.00,'Brazilian Amazon near Manaus','South America','southamerica.html'],
['Surinam Toad','Pipa pipa','🐸','amphibians','Least Concern','Pipa_pipa',5.50,-55.00,'Suriname Coastal Swamps','South America','southamerica.html'],
// ── EUROPE ────────────────────────────────────────────────────────────────────
['European Brown Bear','Ursus arctos arctos','🐻','mammals','Least Concern','Brown_bear',43.50,22.00,'Rhodope Mountains, Bulgaria','Europe','europe.html'],
['Eurasian Lynx','Lynx lynx','🐱','mammals','Least Concern','Eurasian_lynx',52.00,22.00,'Białowieża Forest, Poland','Europe','europe.html'],
['European Bison','Bison bonasus','🦬','mammals','Near Threatened','European_bison',52.70,24.00,'Białowieża Primeval Forest, Poland','Europe','europe.html'],
['Iberian Lynx','Lynx pardinus','🐱','mammals','Endangered','Iberian_lynx',37.50,-6.50,'Coto Doñana, Andalusia, Spain','Europe','europe.html'],
['Gray Wolf (Europe)','Canis lupus','🐺','mammals','Least Concern','Gray_wolf',42.00,13.50,'Abruzzo National Park, Italy','Europe','europe.html'],
['Mediterranean Monk Seal','Monachus monachus','🦭','mammals','Endangered','Mediterranean_monk_seal',37.50,27.00,'Aegean Sea, Turkish Coast','Europe','europe.html'],
['Eurasian Otter','Lutra lutra','🦦','mammals','Near Threatened','Eurasian_otter',56.00,-4.00,'Scottish Highlands, River Tay','Europe','europe.html'],
['European Beaver','Castor fiber','🦫','mammals','Least Concern','European_beaver',52.50,9.00,'Lower Saxony Rivers, Germany','Europe','europe.html'],
['Alpine Ibex','Capra ibex','🐐','mammals','Least Concern','Alpine_ibex',45.83,7.37,'Gran Paradiso National Park, Italy','Europe','europe.html'],
['Chamois','Rupicapra rupicapra','🐐','mammals','Least Concern','Chamois',46.50,8.50,'Swiss Alps, Canton of Uri','Europe','europe.html'],
['Red Deer','Cervus elaphus','🦌','mammals','Least Concern','Red_deer',57.00,-5.00,'Scottish Highlands','Europe','europe.html'],
['Fin Whale','Balaenoptera physalus','🐋','mammals','Vulnerable','Fin_whale',38.00,9.00,'Ligurian Sea, Pelagos Sanctuary','Europe','europe.html'],
['European Hedgehog','Erinaceus europaeus','🦔','mammals','Vulnerable','Western_European_hedgehog',51.50,-0.10,'London Parks, England','Europe','europe.html'],
['European Wildcat','Felis silvestris silvestris','🐱','mammals','Least Concern','European_wildcat',38.00,15.00,'Aspromonte, Calabria, Italy','Europe','europe.html'],
['European Polecat','Mustela putorius','🦡','mammals','Least Concern','European_polecat',52.00,-3.50,'Mid-Wales','Europe','europe.html'],
['European Hare','Lepus europaeus','🐰','mammals','Least Concern','European_hare',51.00,0.50,'Kent, England','Europe','europe.html'],
['European Mink','Mustela lutreola','🦡','mammals','Critically Endangered','European_mink',46.50,25.50,'Danube Delta, Romania','Europe','europe.html'],
['Common Seal','Phoca vitulina','🦭','mammals','Least Concern','Harbour_seal',58.50,-3.00,'Moray Firth, Northern Scotland','Europe','europe.html'],
['Atlantic Bottlenose Dolphin','Tursiops truncatus','🐬','mammals','Least Concern','Common_bottlenose_dolphin',43.50,-8.50,'Galician Coast, NW Spain','Europe','europe.html'],
['Wolverine (Europe)','Gulo gulo','🦡','mammals','Least Concern','Wolverine_(animal)',68.00,18.00,'Scandinavian Mountains, Norway','Europe','europe.html'],
['Loggerhead Sea Turtle','Caretta caretta','🐢','reptiles','Vulnerable','Loggerhead_sea_turtle',37.79,20.90,'Zakynthos (Laganas Bay), Greece','Europe','europe.html'],
['Eurasian Green Lizard','Lacerta viridis','🦎','reptiles','Least Concern','Green_lizard',47.50,18.00,'Danube Plain, Hungary','Europe','europe.html'],
['Horned Viper','Vipera ammodytes','🐍','reptiles','Least Concern','Vipera_ammodytes',43.00,17.50,'Dalmatian Coast, Croatia','Europe','europe.html'],
['European Pond Turtle','Emys orbicularis','🐢','reptiles','Near Threatened','European_pond_turtle',44.00,18.00,'Una River, Bosnia','Europe','europe.html'],
['Asp Viper','Vipera aspis','🐍','reptiles','Least Concern','Asp_viper',44.50,6.50,'Maritime Alps, France/Italy','Europe','europe.html'],
['European Glass Lizard','Pseudopus apodus','🦎','reptiles','Least Concern','European_glass_lizard',38.50,21.50,'Western Greece','Europe','europe.html'],
['White-tailed Eagle','Haliaeetus albicilla','🦅','birds','Least Concern','White-tailed_eagle',54.00,16.50,'Pomeranian Bay, Poland','Europe','europe.html'],
['Peregrine Falcon','Falco peregrinus','🦅','birds','Least Concern','Peregrine_falcon',53.50,-2.50,'Northern England, Lancashire','Europe','europe.html'],
['Great Bustard','Otis tarda','🐦','birds','Vulnerable','Great_bustard',39.50,-5.50,'Extremadura, Spain','Europe','europe.html'],
['White Stork','Ciconia ciconia','🦢','birds','Least Concern','White_stork',52.30,16.50,'Wielkopolska, Poland','Europe','europe.html'],
['Common Kingfisher','Alcedo atthis','🐦','birds','Least Concern','Common_kingfisher',51.50,-2.00,'River Avon, Southern England','Europe','europe.html'],
['Eurasian Eagle Owl','Bubo bubo','🦉','birds','Least Concern','Eurasian_eagle-owl',46.00,9.00,'Swiss Alps, Ticino','Europe','europe.html'],
['Eurasian Bee-eater','Merops apiaster','🐦','birds','Least Concern','European_bee-eater',39.00,-6.00,'Extremadura, Spain','Europe','europe.html'],
['Eurasian Roller','Coracias garrulus','🐦','birds','Least Concern','European_roller',38.00,-5.00,'Extremadura Dehesa, Spain','Europe','europe.html'],
['Common Crane','Grus grus','🦢','birds','Least Concern','Common_crane',54.00,12.50,'Mecklenburg Lakes, Germany','Europe','europe.html'],
['Black Woodpecker','Dryocopus martius','🐦','birds','Least Concern','Black_woodpecker',50.00,15.00,'Šumava National Park, Czech Republic','Europe','europe.html'],
['European Nightjar','Caprimulgus europaeus','🐦','birds','Least Concern','European_nightjar',51.00,0.50,'Surrey Heathland, England','Europe','europe.html'],
['Barn Swallow','Hirundo rustica','🐦','birds','Least Concern','Barn_swallow',52.00,5.00,'Dutch Polders, Netherlands','Europe','europe.html'],
['Short-toed Snake Eagle','Circaetus gallicus','🦅','birds','Least Concern','Short-toed_snake_eagle',40.00,15.00,'Cilento, Southern Italy','Europe','europe.html'],
['Eurasian Spoonbill','Platalea leucorodia','🦢','birds','Least Concern','Eurasian_spoonbill',52.80,5.20,'Wadden Sea, Netherlands','Europe','europe.html'],
['Atlantic Bluefin Tuna','Thunnus thynnus','🐟','fish','Least Concern','Atlantic_bluefin_tuna',38.00,5.00,'Western Mediterranean, Ligurian Sea','Europe','europe.html'],
['European Eel','Anguilla anguilla','🐟','fish','Critically Endangered','European_eel',51.50,5.00,'Dutch Rhine-Meuse Delta','Europe','europe.html'],
['Atlantic Salmon','Salmo salar','🐟','fish','Least Concern','Atlantic_salmon',57.00,-5.00,'River Tay, Scottish Highlands','Europe','europe.html'],
['Wels Catfish','Silurus glanis','🐟','fish','Least Concern','Wels_catfish',48.00,17.00,'Danube River, Slovakia','Europe','europe.html'],
['Basking Shark','Cetorhinus maximus','🦈','fish','Endangered','Basking_shark',56.50,-5.50,'Sea of the Hebrides, Scotland','Europe','europe.html'],
['European Sturgeon','Acipenser sturio','🐟','fish','Critically Endangered','European_sea_sturgeon',44.50,-1.00,'Gironde Estuary, France','Europe','europe.html'],
['Zander','Sander lucioperca','🐟','fish','Least Concern','Zander',52.00,14.00,'German Lakes, Brandenburg','Europe','europe.html'],
['Common Carp','Cyprinus carpio','🐟','fish','Vulnerable','Common_carp',47.50,19.00,'Danube Floodplain, Hungary','Europe','europe.html'],
['Stag Beetle','Lucanus cervus','🪲','insects','Near Threatened','Stag_beetle',51.50,-0.10,'Richmond Park, London','Europe','europe.html'],
['European Honey Bee','Apis mellifera','🐝','insects','Data Deficient','Western_honey_bee',47.00,8.00,'Swiss Alps Meadows','Europe','europe.html'],
['Great Yellow Bumblebee','Bombus distinguendus','🐝','insects','Least Concern','Great_yellow_bumblebee',58.50,-4.50,'Northern Scottish Highlands','Europe','europe.html'],
['Spanish Moon Moth','Graellsia isabellae','🦋','insects','Least Concern','Graellsia_isabellae',40.50,-1.50,'Cuenca Mountains, Spain','Europe','europe.html'],
['Alpine Longhorn Beetle','Rosalia alpina','🪲','insects','Vulnerable','Rosalia_alpina',46.00,8.00,'Swiss Ticino Alps','Europe','europe.html'],
['Violet Ground Beetle','Carabus violaceus','🪲','insects','Least Concern','Carabus_violaceus',52.00,1.00,'Norfolk, East Anglia','Europe','europe.html'],
['Fire Salamander','Salamandra salamandra','🔥','amphibians','Least Concern','Fire_salamander',48.00,11.50,'Bavarian Forest, Germany','Europe','europe.html'],
['Great Crested Newt','Triturus cristatus','🐸','amphibians','Least Concern','Great_crested_newt',52.50,1.00,'Norfolk Broads, England','Europe','europe.html'],
['Olm','Proteus anguinus','🐸','amphibians','Vulnerable','Olm',45.80,14.00,'Postojna Cave System, Slovenia','Europe','europe.html'],
['European Tree Frog','Hyla arborea','🐸','amphibians','Least Concern','European_tree_frog',47.50,8.50,'Swiss Mittelland','Europe','europe.html'],
['Yellow-bellied Toad','Bombina variegata','🐸','amphibians','Least Concern','Yellow-bellied_toad',48.00,12.50,'Bavarian Foreland, Germany','Europe','europe.html'],
['Common Midwife Toad','Alytes obstetricans','🐸','amphibians','Least Concern','Common_midwife_toad',43.00,-3.50,'Pyrenean Foothills, Northern Spain','Europe','europe.html'],
// ── OCEANIA ───────────────────────────────────────────────────────────────────
['Red Kangaroo','Macropus rufus','🦘','mammals','Least Concern','Red_kangaroo',-25.00,134.00,'Central Australia, NT','Oceania','oceania.html'],
['Common Wombat','Vombatus ursinus','🐾','mammals','Least Concern','Common_wombat',-36.00,148.00,'Kosciuszko National Park, NSW','Oceania','oceania.html'],
['Koala','Phascolarctos cinereus','🐨','mammals','Vulnerable','Koala',-27.00,153.00,'Southeast Queensland','Oceania','oceania.html'],
['Platypus','Ornithorhynchus anatinus','🦆','mammals','Near Threatened','Platypus',-37.00,149.00,'Snowy River, NSW/VIC Border','Oceania','oceania.html'],
['Short-beaked Echidna','Tachyglossus aculeatus','🦔','mammals','Least Concern','Short-beaked_echidna',-33.00,151.00,'NSW National Parks','Oceania','oceania.html'],
['Tasmanian Devil','Sarcophilus harrisii','😈','mammals','Endangered','Tasmanian_devil',-43.00,147.00,'Freycinet Peninsula, Tasmania','Oceania','oceania.html'],
['Quokka','Setonix brachyurus','🦘','mammals','Vulnerable','Quokka',-32.00,115.60,'Rottnest Island, Western Australia','Oceania','oceania.html'],
['Dingo','Canis lupus dingo','🐕','mammals','Vulnerable','Dingo',-26.00,131.00,'Uluru-Kata Tjuta, NT','Oceania','oceania.html'],
['Dugong','Dugong dugon','🐘','mammals','Vulnerable','Dugong',-16.00,146.00,'Great Barrier Reef lagoon, Queensland','Oceania','oceania.html'],
['Southern Right Whale','Eubalaena australis','🐋','mammals','Least Concern','Southern_right_whale',-35.00,136.00,'Great Australian Bight','Oceania','oceania.html'],
["Lumholtz's Tree-kangaroo",'Dendrolagus lumholtzi','🦘','mammals','Near Threatened','Lumholtz\'s_tree-kangaroo',-17.00,145.00,'Queensland Wet Tropics','Oceania','oceania.html'],
['Eastern Quoll','Dasyurus viverrinus','🐾','mammals','Endangered','Eastern_quoll',-43.50,147.00,'Bruny Island, Tasmania','Oceania','oceania.html'],
['Sugar Glider','Petaurus breviceps','🐾','mammals','Least Concern','Sugar_glider',-33.00,151.00,'Blue Mountains, NSW','Oceania','oceania.html'],
['Numbat','Myrmecobius fasciatus','🦡','mammals','Endangered','Numbat',-33.00,117.00,'Dryandra Woodland, Western Australia','Oceania','oceania.html'],
["Leadbeater's Possum",'Gymnobelideus leadbeateri','🐾','mammals','Critically Endangered','Leadbeater\'s_possum',-37.50,145.70,'Victorian Alps, Central Highlands','Oceania','oceania.html'],
['Sperm Whale','Physeter macrocephalus','🐳','mammals','Vulnerable','Sperm_whale',-40.00,175.00,'Kaikōura, New Zealand','Oceania','oceania.html'],
['Indo-Pacific Bottlenose Dolphin','Tursiops aduncus','🐬','mammals','Least Concern','Indo-Pacific_bottlenose_dolphin',-25.00,113.00,'Shark Bay, Western Australia','Oceania','oceania.html'],
['Saltwater Crocodile','Crocodylus porosus','🐊','reptiles','Least Concern','Saltwater_crocodile',-12.50,130.00,'Adelaide River, Northern Territory','Oceania','oceania.html'],
['Inland Taipan','Oxyuranus microlepidotus','🐍','reptiles','Least Concern','Inland_taipan',-28.00,141.00,'Channel Country, SW Queensland','Oceania','oceania.html'],
['Frilled-neck Lizard','Chlamydosaurus kingii','🦎','reptiles','Least Concern','Frilled-neck_lizard',-15.00,131.00,'Pine Creek, Northern Territory','Oceania','oceania.html'],
['Thorny Devil','Moloch horridus','🦎','reptiles','Least Concern','Thorny_devil',-25.00,126.00,'Great Victoria Desert, WA','Oceania','oceania.html'],
['Green Sea Turtle','Chelonia mydas','🐢','reptiles','Endangered','Green_sea_turtle',-23.50,152.00,'Great Barrier Reef, Queensland','Oceania','oceania.html'],
['Lace Monitor','Varanus varius','🦎','reptiles','Least Concern','Lace_monitor',-33.00,152.00,'Ku-ring-gai Chase NP, NSW','Oceania','oceania.html'],
['Hawksbill Sea Turtle','Eretmochelys imbricata','🐢','reptiles','Critically Endangered','Hawksbill_sea_turtle',-16.00,145.00,'Coral Sea, Great Barrier Reef','Oceania','oceania.html'],
['Emu','Dromaius novaehollandiae','🦤','birds','Least Concern','Emu',-25.00,121.00,'Murchison, Western Australia','Oceania','oceania.html'],
['Southern Cassowary','Casuarius casuarius','🦤','birds','Vulnerable','Southern_cassowary',-17.00,145.80,'Daintree Rainforest, Queensland','Oceania','oceania.html'],
['Laughing Kookaburra','Dacelo novaeguineae','🐦','birds','Least Concern','Laughing_kookaburra',-33.00,151.00,'Sydney, NSW','Oceania','oceania.html'],
['Sulphur-crested Cockatoo','Cacatua galerita','🦜','birds','Least Concern','Sulphur-crested_cockatoo',-33.00,151.00,'Sydney Suburban Areas, NSW','Oceania','oceania.html'],
['Superb Lyrebird','Menura novaehollandiae','🐦','birds','Least Concern','Superb_lyrebird',-38.00,145.00,'Dandenong Ranges, Victoria','Oceania','oceania.html'],
['Wedge-tailed Eagle','Aquila audax','🦅','birds','Least Concern','Wedge-tailed_eagle',-25.00,128.00,'Gibson Desert, WA','Oceania','oceania.html'],
['Satin Bowerbird','Ptilonorhynchus violaceus','🐦','birds','Least Concern','Satin_bowerbird',-35.00,149.00,'Brindabella Ranges, ACT','Oceania','oceania.html'],
['Kakapo','Strigops habroptilus','🦜','birds','Critically Endangered','Kakapo',-46.00,167.00,'Whenua Hou (Codfish Island), New Zealand','Oceania','oceania.html'],
['Brown Kiwi','Apteryx australis','🐦','birds','Vulnerable','Brown_kiwi',-39.00,176.00,"Hawke's Bay, North Island, New Zealand",'Oceania','oceania.html'],
['Tui','Prosthemadera novaeseelandiae','🐦','birds','Least Concern','Tui_(bird)',-36.87,174.76,'Waitakere Ranges, Auckland, NZ','Oceania','oceania.html'],
['Black Swan','Cygnus atratus','🦢','birds','Least Concern','Black_swan',-31.00,115.80,'Swan River, Perth, Western Australia','Oceania','oceania.html'],
['Little Penguin','Eudyptula minor','🐧','birds','Least Concern','Little_penguin',-38.30,145.10,'Phillip Island, Victoria','Oceania','oceania.html'],
['Rainbow Lorikeet','Trichoglossus moluccanus','🦜','birds','Least Concern','Rainbow_lorikeet',-27.00,153.00,'Brisbane, Queensland','Oceania','oceania.html'],
['Superb Fairy-wren','Malurus cyaneus','🐦','birds','Least Concern','Superb_fairywren',-35.00,149.00,'Canberra Nature Parks, ACT','Oceania','oceania.html'],
['Whale Shark','Rhincodon typus','🦈','fish','Endangered','Whale_shark',-23.00,113.00,'Ningaloo Reef, Western Australia','Oceania','oceania.html'],
['Leafy Sea Dragon','Phycodurus eques','🐟','fish','Least Concern','Leafy_seadragon',-35.00,137.00,'Yorke Peninsula, South Australia','Oceania','oceania.html'],
['Barramundi','Lates calcarifer','🐟','fish','Least Concern','Barramundi',-15.00,131.00,'Daly River, Northern Territory','Oceania','oceania.html'],
['Murray Cod','Maccullochella peelii','🐟','fish','Vulnerable','Murray_cod',-34.50,143.00,'Murray River, Victoria/NSW','Oceania','oceania.html'],
['Reef Manta Ray','Mobula alfredi','🐟','fish','Vulnerable','Reef_manta_ray',-23.00,113.00,'Ningaloo Reef, WA','Oceania','oceania.html'],
['Epaulette Shark','Hemiscyllium ocellatum','🦈','fish','Least Concern','Epaulette_shark',-18.00,147.00,'Lizard Island, Great Barrier Reef','Oceania','oceania.html'],
['Potato Cod','Epinephelus tukula','🐟','fish','Vulnerable','Potato_grouper',-15.00,146.00,'Cod Hole, Ribbon Reefs, GBR','Oceania','oceania.html'],
['Ulysses Butterfly','Papilio ulysses','🦋','insects','Least Concern','Ulysses_butterfly',-17.00,145.70,'Daintree Rainforest, Queensland','Oceania','oceania.html'],
['Lord Howe Island Stick Insect','Dryococelus australis','🪲','insects','Critically Endangered','Dryococelus_australis',-31.60,159.00,"Ball's Pyramid, Lord Howe Island",'Oceania','oceania.html'],
['Giant Burrowing Cockroach','Macropanesthia rhinocephala','🪲','insects','Least Concern','Giant_burrowing_cockroach',-17.00,145.00,'Tropical Queensland','Oceania','oceania.html'],
['Bull Ant','Myrmecia gulosa','🐜','insects','Least Concern','Bull_ant',-35.00,149.00,'Canberra Bushland, ACT','Oceania','oceania.html'],
['Green Tree Frog','Litoria caerulea','🐸','amphibians','Least Concern','Australian_green_tree_frog',-15.00,133.00,'Darwin, Northern Territory','Oceania','oceania.html'],
['Corroboree Frog','Pseudophryne corroboree','🐸','amphibians','Critically Endangered','Southern_corroboree_frog',-36.50,148.50,'Kosciuszko National Park, NSW','Oceania','oceania.html'],
['Water-holding Frog','Cyclorana platycephala','🐸','amphibians','Least Concern','Water-holding_frog',-25.00,134.00,'Simpson Desert, Central Australia','Oceania','oceania.html'],
['Giant White-lipped Tree Frog','Litoria infrafrenata','🐸','amphibians','Least Concern','White-lipped_tree_frog',-9.00,148.00,'PNG Eastern Highlands','Oceania','oceania.html'],
['Tusked Frog','Adelotus brevis','🐸','amphibians','Least Concern','Tusked_frog',-27.00,152.00,'Sunshine Coast Hinterland, SE Queensland','Oceania','oceania.html'],
['Magnificent Tree Frog','Litoria splendida','🐸','amphibians','Least Concern','Magnificent_tree_frog',-17.00,125.00,'Kimberley, Western Australia','Oceania','oceania.html'],
];

var ALL_ANIMALS=_D.map(function(d){
  return{name:d[0],scientific:d[1],emoji:d[2],category:d[3],
    status:d[4],wiki:d[5],lat:d[6],lon:d[7],habitat:d[8],
    continent:d[9],continentFile:d[10]};
});
